### ISSUE TITLE
Remake all benchmarks using proper technique

### ISSUE THREAD

**Issue by Mart-Bogdan** [atamurius/error-handling-banchmark#1]
1. Use JMH framework for benchmark.
2. simulate deep stack (exception or error is thrown from depth of several invocation, not directly caught), plus with some finally blocks, or handling logic on ADT in child methods. This copud be another set of benchmarks.

Why second one is just for sake of completeness of benchmark, but first one is MUST HAVE, as otherwise results are incorrect,

**Comment by atamurius** [comment]
JMH is not the only tool for correct benchmarks.
As for deep call stack, it may be interesting, but even in such small
example exceptions are already very slow.

чт, 6 дек. 2018 г., 23:43 Bogdan Mart notifications@github.com:
